### ISSUE TITLE
The commit history of all repos should be kept clear

### ISSUE THREAD

**Issue by erciccione** [bisq-network/style#14]
At the moment there is no workflow in place for the maintainement of the git history. This results in all bisq repositories having a very messy and heavy history. There are also many merge commits inside pull requests, which got merged. That is an extremely discouraged approach, since merge commits (beside messing with the git tree) make things even harder to read. It's currently impossible to effectively browse the git history.

Maintainers and contributors should both take care of the problem and make sure only meaningful and self-contained commits are merged.

An easy but effective workflow would be:

1. Contributors are asked to squash their commits and keep history clean (workflow introduced with bisq-network/bisq#3217)
2. If the contributor hasn't squashed or there are merge commits in the PR, the **maintainers should use the *Squash and Merge* option when merging**.

I think these two ways of handle contributions and commits should be introduced as soon as possible.

**Comment by blabno** [comment]
I don't think that rubbish should be merged, no matter what form:
- rubbish functionality
- rubbish code
- rubbish commit history

**Comment by freimair** [comment]
- agree on 1
- disagree on 2, as (in my role as maintainer) this takes to much effort and time to do the squash.

**Comment by erciccione** [comment]
@freimair I think the point is to start enforce 1 only accepting high quality pull requests, 2 is of secondary importance. The point is to have everything as clean as clear as possible.
